### ISSUE TITLE
bnd node does not appear in TransModification (LigandModification)

### ISSUE THREAD

**Issue by slegare2** [Kappa-Dev/KAMI#16]
Maybe I do not use enzyme_bnd_region and substrate_bnd_region correctly, but when I run the following script:

```
from kami.entities import (Gene, Region, Site, Residue, State, RegionActor, SiteActor)
from kami.interactions import (Binding, Unbinding, Modification, TransModification, AutoModification)
from kami.hierarchy import (KamiHierarchy)
from regraph import print_graph

inter = TransModification(
    enzyme=RegionActor(gene=Gene(uniprotid="P30530",
                                 hgnc_symbol="AXL"),
                       region=Region(name="Tyr_kinase",
                                     interproid="IPR020635",
                                     start=536, end=807)),
    substrate=SiteActor(gene=Gene(uniprotid="P06239",
                                  hgnc_symbol="LCK"),
                        site=Site(name="pY394",
                                  start=391, end=397)),
    target=Residue(aa="Y", loc=394,
                   state=State("phosphorylation", False)),
    value=True,
    rate=10,
    enzyme_bnd_region=Region(name="Tyr_kinase",
                              interproid="IPR020635",
                              start=536, end=807),
    substrate_bnd_site=Site(name='pY394',
                             start=391, end=397)
)

hierarchy = KamiHierarchy()
hierarchy.add_interaction(inter, anatomize=False)

print(inter)
print("printing nugget_1")
print_graph(hierarchy.graph['nugget_1'])
```
I get no bnd node in the nugget:
```
TransModification:
	Enzyme: region_Tyr_kinase_IPR020635_536_807_P30530
	Substrate: P06239_[]_site_pY394_391_397
	Mod target: Y394
	Value: True
	Enzyme binding region: region_Tyr_kinase_IPR020635_536_807
	Substrate binding site: site_pY394_391_397
	Rate: 10

printing nugget_1

Nodes:

P30530  :  {'uniprotid': {'P30530'}, 'hgnc_symbol': {'AXL'}}
P30530_region_Tyr_kinase_IPR020635_536_807  :  {'interproid': {'IPR020635'}, 'name': {'Tyr_kinase'}}
P06239  :  {'uniprotid': {'P06239'}, 'hgnc_symbol': {'LCK'}}
P06239_site_pY394_391_397  :  {'name': {'pY394'}}
mod  :  {'rate': {5}, 'value': {True}}
P06239_site_pY394_391_397_Y394  :  {'aa': {'Y'}, 'test': {True}}
P06239_site_pY394_391_397_Y394_phosphorylation  :  {'name': {'phosphorylation'}, 'test': {False}}

Edges:

P30530_region_Tyr_kinase_IPR020635_536_807 -> P30530  :  {'start': {536}, 'end': {807}}
P30530_region_Tyr_kinase_IPR020635_536_807 -> mod  :  {}
P06239_site_pY394_391_397 -> P06239  :  {'start': {391}, 'end': {397}}
mod -> P06239_site_pY394_391_397_Y394_phosphorylation  :  {}
P06239_site_pY394_391_397_Y394 -> P06239_site_pY394_391_397  :  {'loc': {394}}
P06239_site_pY394_391_397_Y394_phosphorylation -> P06239_site_pY394_391_397_Y394  :  {}
```

**Comment by eugeniashurko** [comment]
Hi!

Thanks for this issue, I found a bug, which was a very funny one. Now everything seems to work.

There is one thing to note in the design of `TransModification`  class though (which I also don't like, but still don't have any better solution). When `enzyme_bnd_region`/`enzyme_bnd_site` is specified (and the same for the substrate) in the nugget, distinct nodes are created, i.e. if you already have your RegionActor kinase that performs modification and then you also say that this is the enzyme binding region (the same object or kinase in the same range let's say) two distinct kinase nodes are created in the nugget: one for the actor of modification and another for the actor of binding. Of course, in the action graph they are identified as the same region, so it shouldn't be a problem for kappa-rule generation. But in case of the nugget graph itself it's still a bit weird. For example, now the result of your script is the following:

```
Nodes:

P30530  :  {'uniprotid': {'P30530'}, 'hgnc_symbol': {'AXL'}}
P30530_region_Tyr_kinase_IPR020635_536_807  :  {'interproid': {'IPR020635'}, 'name': {'Tyr_kinase'}}
P06239  :  {'uniprotid': {'P06239'}, 'hgnc_symbol': {'LCK'}}
P06239_site_pY394_391_397  :  {'name': {'pY394'}}
mod  :  {'rate': {10}, 'value': {True}}
P06239_site_pY394_391_397_Y394  :  {'aa': {'Y'}, 'test': {True}}
P06239_site_pY394_391_397_Y394_phosphorylation  :  {'name': {'phosphorylation'}, 'test': {False}}
P30530_region_Tyr_kinase_IPR020635_536_807_1  :  {'interproid': {'IPR020635'}, 'name': {'Tyr_kinase'}}
P06239_site_pY394_391_397_1  :  {'name': {'pY394'}}
is_bnd  :  {'type': {'be'}, 'test': {True}}

Edges:

P30530_region_Tyr_kinase_IPR020635_536_807 -> P30530  :  {'start': {536}, 'end': {807}}
P30530_region_Tyr_kinase_IPR020635_536_807 -> mod  :  {}
P06239_site_pY394_391_397 -> P06239  :  {'start': {391}, 'end': {397}}
mod -> P06239_site_pY394_391_397_Y394_phosphorylation  :  {}
P06239_site_pY394_391_397_Y394 -> P06239_site_pY394_391_397  :  {'loc': {394}}
P06239_site_pY394_391_397_Y394_phosphorylation -> P06239_site_pY394_391_397_Y394  :  {}
P30530_region_Tyr_kinase_IPR020635_536_807_1 -> P30530  :  {'start': {536}, 'end': {807}}
P30530_region_Tyr_kinase_IPR020635_536_807_1 -> is_bnd  :  {}
P06239_site_pY394_391_397_1 -> P06239  :  {'start': {391}, 'end': {397}}
P06239_site_pY394_391_397_1 -> is_bnd  :  {}
```

**Comment by slegare2** [comment]
Thanks!
But effectively, two kinase regions is not what I intended. This problem seems to come back in several occasions. When we don't know if two nodes inside an interaction are actually the same. We really need a way to specify this. Could we add something like a "same" parameter to entities? It would be set to False by default, but when a user would set it to True, the algorithm would match the entity with any other entities within the interaction that are identified exactly in the same way (same "name", "start", "end", etc).

**Comment by eugeniashurko** [comment]
Yes, we should do something like this. But there is a lot of possible combinations of `same` entities, and this is the biggest problem, so our data structure can easily explode. Also, the usual strategy of our input/nugget generation pipeline is that the identification (so, the identification of things by "name", "start", "end") is done only relatively to the action graph and KAMI interaction objects define nuggets in some more syntactic way. In any case, we still need to think how can we represent this stuff. What I think would be more realistic is to have a flag to specify if in our RegionActor/SiteActor object bnd is performed by one of the components, so you would have something like this:

```
inter = TransModification(
    enzyme=RegionActor(gene=Gene(uniprotid="P30530",
                                 hgnc_symbol="AXL"),
                       region=Region(name="Tyr_kinase",
                                     interproid="IPR020635",
                                     start=536, end=807)),
    substrate=SiteActor(gene=Gene(uniprotid="P06239",
                                  hgnc_symbol="LCK"),
                        site=Site(name="pY394",
                                  start=391, end=397)),
    target=Residue(aa="Y", loc=394,
                   state=State("phosphorylation", False)),
    value=True,
    rate=10,
    enzyme_bnd_subactor="region",
    substrate_bnd_subactor="site",
    enzyme_bnd_site=Site(name="Site_of_Tyr_kinase_to_bind",
                              start=550, end=660),
)
```

Where we would have just two new arguments `enzyme_bnd_subactor` and `substrate_bnd_subactor` which can take values in `gene`, `region`, `site`, with the default one being `gene`. Then 
`enzyme_bnd_region`/`enzyme_bnd_site` are interpreted as the one belonging to the  `enzyme_bnd_subactor` entity (the same for the substrate)

**Comment by slegare2** [comment]
I think I do not understand. If the "same" argument is used just within a single interaction, shouldn't there be very few possible combinations? I do not want to specify if it is the same entity as that of other nuggets.

But anyway, the solution you propose looks great. In my specific case, I want to binding to occur between the enzyme region "Tyr_kinase" and the substrate site "pY394". So I would just need to write
```
enzyme_bnd_subactor="region",
substrate_bnd_subactor="site"
```
and would not even need to use ```enzyme_bnd_site```, right?

**Comment by eugeniashurko** [comment]
Yes, exactly! I added `enzyme_bnd_site` to illustrate that you can even specify some additional stuff, but now it is related to the entity which is `enzyme_bnd_subactor`. For, example if  `enzyme_bnd_subactor` is `site` you cannot specify `enzyme_bnd_site` and you get an error (as we do not allow nested sites). 

I am not implementing it yet, because i want some time to think it through and see if it is able  to express everything we want
