### ISSUE TITLE
Cannot import AttributeSetError

### ISSUE THREAD

**Issue by slegare2** [Kappa-Dev/KAMI#6]
First got
```
File "kami/hierarchy.py", line 8, in <module>
    from regraph import Rule, Hierarchy
ImportError: cannot import name 'Rule'
```
Changed line 8 in hierarchy.py to
```
from regraph.rules import Rule
from regraph.hierarchy import Hierarchy
```
Now I get error
```
File "regraph/attribute_sets.py", line 34, in <module>
    from regraph.exceptions import AttributeSetError
ImportError: cannot import name 'AttributeSetError'
```

**Comment by eugeniashurko** [comment]
Hi, did you try to reinstall ReGraph to the newest version (master branch)? Seems bizarre, cause everything should work according to `ReGraph/regraph/__init__.py`, but I will check now myself

**Comment by slegare2** [comment]
Hi,

Sorry took a while to answer, I was at my favorite place in Lyon...
Yea, I had forgotten to switch back to master branch in ReGraph. Sorry
about this one. It all works well now.

Sebastien
